"""
Django settings for QR_Attendance_System project.

Generated by 'django-admin startproject' using Django 4.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os.path
import glob

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

conffiles = glob.glob(os.path.join(os.path.dirname(__file__), 'settings', '*.conf.py'))
conffiles.sort()
for f in conffiles:
    with open(f) as ff:
        code = compile(ff.read(), f, 'exec')
        exec(code,globals(),locals())
